// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function CheckLicense(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3969589005) as any;
    return $resultPromise;
}

export function LoginAndGetTicket(username: string, password: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3060580648, username, password) as any;
    return $resultPromise;
}

export function VerifyKey(key: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2534983810, key) as any;
    return $resultPromise;
}
